# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Empire-Mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'PKHUD', '~> 5.0'
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 4.0'
  # Pods for Empire-Mobile

  target 'Empire-MobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Empire-MobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
